-- 챌린지 정의 테이블 생성
CREATE TABLE challenge_definition (
    id BIGSERIAL PRIMARY KEY,
    content VARCHAR(255) NOT NULL, -- 챌린지 내용
    emotion_type VARCHAR(20) NOT NULL, -- 감정 유형 (JOY, SADNESS, ANGER, APATHY, SENSITIVE)
    category VARCHAR(50), -- 활동 카테고리 (운동, 루틴, 명상 등)
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 인덱스 추가 (emotion_type 자주 조회되므로)
CREATE INDEX idx_challenge_definition_emotion_type ON challenge_definition(emotion_type);

-- SADNESS (30개)
INSERT INTO challenge_definition (content, emotion_type, category) VALUES
('500보 이상 산책하기', 'SADNESS', '운동'),
('친구에게 안부 메시지 보내기', 'SADNESS', '사회'),
('따뜻한 차 마시기', 'SADNESS', '휴식'),
('좋아하는 노래 듣기', 'SADNESS', '음악'),
('책 한 줄 필사하기', 'SADNESS', '루틴'),
('조용한 곳에서 책 30분 읽기', 'SADNESS', '루틴'),
('OTT 켜서 처음 나오는 영화 보기', 'SADNESS', '휴식'),
('캔들 켜고 20분 쉬기', 'SADNESS', '휴식'),
('미래의 나에게 편지 쓰기', 'SADNESS', '사회'),
('오늘 마음을 색으로 표현하기', 'SADNESS', '창작'),
('창문 열고 하늘 보기', 'SADNESS', '운동'),
('따뜻한 샤워하기', 'SADNESS', '휴식'),
('가볍게 5분 명상하기', 'SADNESS', '명상'),
('분리수거 하기', 'SADNESS', '루틴'),
('클래식 음악 틀기', 'SADNESS', '음악'),
('모르는 사람이랑 대화하기', 'SADNESS', '사회'),
('햇볕 받으며 앉아 있기', 'SADNESS', '휴식'),
('미지근한 물 500ml 마시기', 'SADNESS', '루틴'),
('달달한 젤리 먹기', 'SADNESS', '루틴'),
('포근한 이불 속에 있기', 'SADNESS', '휴식'),
('마음을 편하게 하는 향 맡기', 'SADNESS', '휴식'),
('짧은 스트레칭', 'SADNESS', '운동'),
('간단한 그림 그리기', 'SADNESS', '창작'),
('1년 전 갤러리 보기', 'SADNESS', '휴식'),
('웃는 얼굴로 셀카 찍기', 'SADNESS', '음악'),
('설거지 하기', 'SADNESS', '루틴'),
('내가 좋아하는 것 목록 적기', 'SADNESS', '루틴'),
('따듯한 차 마시기', 'SADNESS', '휴식'),
('버킷리스트 3개 적기', 'SADNESS', '루틴'),
('배경화면 바꿔보기', 'SADNESS', '루틴');

-- ANGER (30개)
INSERT INTO challenge_definition (content, emotion_type, category) VALUES
('심호흡 5분 하기', 'ANGER', '명상'),
('스트레스 줄여주는 주파수 듣기', 'ANGER', '음악'),
('5분 이상 산책하기', 'ANGER', '운동'),
('스트레스 종이에 연필로 적고 찢기', 'ANGER', '창작'),
('찬물 세수하기', 'ANGER', '휴식'),
('가벼운 요가 동작', 'ANGER', '운동'),
('명상 5분 이상 하기', 'ANGER', '명상'),
('노래방 가기', 'ANGER', '운동'),
('좋아하는 차 마시기', 'ANGER', '휴식'),
('상대방에게 하고 싶은 말 편지에 쓰기', 'ANGER', '창작'),
('집안 정리하기', 'ANGER', '루틴'),
('책상 청소하기', 'ANGER', '루틴'),
('아이스크림 먹기', 'ANGER', '루틴'),
('창문 열고 환기하기', 'ANGER', '루틴'),
('좋아하는 색으로 낙서하기', 'ANGER', '창작'),
('찬 물로 손 씻기', 'ANGER', '휴식'),
('손목 스트레칭', 'ANGER', '운동'),
('심호흡 10회', 'ANGER', '명상'),
('얼음물 마시기', 'ANGER', '휴식'),
('친구랑 5분 전화하기', 'ANGER', '사회'),
('자연 소리 5분 듣기', 'ANGER', '휴식'),
('불 끄고 눈 감기', 'ANGER', '휴식'),
('노트에 화난 감정 쓰기', 'ANGER', '루틴'),
('화났을 때 내 표정 그리기', 'ANGER', '창작'),
('매운 음식 먹기', 'ANGER', '휴식'),
('편의점에서 간단한 간식 사기', 'ANGER', '루틴'),
('유튜브 들어가서 처음 뜨는 영상 보고 끄기', 'ANGER', '루틴'),
('재밌는 예능 영상 보기', 'ANGER', '루틴'),
('양치하기', 'ANGER', '루틴'),
('좋은 기억 떠올리기', 'ANGER', '루틴');

-- APATHY (무기력, 30개)
INSERT INTO challenge_definition (content, emotion_type, category) VALUES
('기지개 펴기', 'APATHY', '운동'),
('책 10쪽 읽기', 'APATHY', '루틴'),
('침대 정리하기', 'APATHY', '루틴'),
('쓰레기 버리기', 'APATHY', '루틴'),
('방 5바퀴 돌기', 'APATHY', '운동'),
('오늘 해야 할 일 1개만 적기', 'APATHY', '루틴'),
('가방 챙기기', 'APATHY', '루틴'),
('핸드폰 10분 동안 내려놓고 멍 때리기', 'APATHY', '루틴'),
('건강체조 따라하기', 'APATHY', '운동'),
('아침에 창문 열기', 'APATHY', '루틴'),
('간단한 헤어스타일 변화주기', 'APATHY', '도전'),
('좋아하는 간식 먹기', 'APATHY', '루틴'),
('간단한 여행 계획 짜기', 'APATHY', '도전'),
('샤워하기', 'APATHY', '루틴'),
('내일 목표 1개 적기', 'APATHY', '루틴'),
('핸드폰 충전시키기', 'APATHY', '루틴'),
('지인에게 안부인사 보내기', 'APATHY', '루틴'),
('가벼운 산책 후 사진 찍기', 'APATHY', '운동'),
('좋아하는 영화 보기', 'APATHY', '휴식'),
('영양제 먹기', 'APATHY', '루틴'),
('편의점 꿀조합 레시피 따라하기', 'APATHY', '도전'),
('안무영상 보고 따라추기', 'APATHY', '운동'),
('급작스러운 약속잡기', 'APATHY', '도전'),
('타자연습 신기록 세우기', 'APATHY', '도전'),
('꽃 한 송이 사기', 'APATHY', '운동'),
('신곡 아무거나 들어보기', 'APATHY', '음악'),
('눈 감고 스크롤 내려서 전화 걸기(기회 3번)', 'APATHY', '도전'),
('쇼핑 리스트 만들기', 'APATHY', '창작'),
('입고 싶은 코디 짜기', 'APATHY', '창작'),
('내가 좋아하는 것 3개 적기', 'APATHY', '루틴');

-- SENSITIVE (불안, 30개)
INSERT INTO challenge_definition (content, emotion_type, category) VALUES
('귀마개 끼고 1시간 있기', 'SENSITIVE', '휴식'),
('눈을 감고 명상 5분 하기', 'SENSITIVE', '명상'),
('잠들기 2시간 전 목욕하기', 'SENSITIVE', '루틴'),
('하루 동안 카페인 섭취 금지하기', 'SENSITIVE', '도전'),
('말랑이 만지기', 'SENSITIVE', '루틴'),
('깊은 호흡하기', 'SENSITIVE', '명상'),
('친구와 이야기 나누기', 'SENSITIVE', '휴식'),
('불안한 요소 글로 정리하기', 'SENSITIVE', '창작'),
('동네 예쁜 카페 가기', 'SENSITIVE', '운동'),
('공원 나가 햇볕 쬐며 앉아있기', 'SENSITIVE', '휴식'),
('짧은 낮잠 자기', 'SENSITIVE', '휴식'),
('길고양이 찾으러 가기', 'SENSITIVE', '운동'),
('핸드폰 끄고 해야할 일 정리하기', 'SENSITIVE', '루틴'),
('GPT에게 객관적인 상황 물어보기', 'SENSITIVE', '사회'),
('사칙연산 문제 10개 풀기', 'SENSITIVE', '루틴'),
('틀린 그림 찾기하기', 'SENSITIVE', '도전'),
('SNS 하루 동안 지우기', 'SENSITIVE', '도전'),
('거울 보고 활짝 웃기', 'SENSITIVE', '루틴'),
('잠들기 전 좋은 말 생각하기', 'SENSITIVE', '루틴'),
('하루 계획 세우고 지키기', 'SENSITIVE', '창작'),
('러닝 30분 하기', 'SENSITIVE', '운동'),
('235호흡법 하기', 'SENSITIVE', '루틴'),
('10분간 생각 멈추기', 'SENSITIVE', '휴식'),
('종이비행기 날려서 멀리 보내기', 'SENSITIVE', '도전'),
('왼손으로만 그림 그리기', 'SENSITIVE', '창작'),
('3분간 방에 있는 초록색 물건 찾기', 'SENSITIVE', '도전'),
('끝말잇기 50 단어 이어하기', 'SENSITIVE', '도전'),
('잘 되는 상상하기', 'SENSITIVE', '창작'),
('손톱깎기', 'SENSITIVE', '루틴'),
('불안한 요소 쓰고 찢기', 'SENSITIVE', '루틴');

-- JOY (기쁨, 30개)
INSERT INTO challenge_definition (content, emotion_type, category) VALUES
('감사 일기 1줄 작성하기', 'JOY', '루틴'),
('오늘을 기억할만한 사진 찍기', 'JOY', '루틴'),
('소소한 간식 즐기기', 'JOY', '휴식'),
('친구에게 칭찬 메시지 보내기', 'JOY', '사회'),
('오늘 좋았던 일 3가지 적기', 'JOY', '루틴'),
('오늘 찍은 사진 보기', 'JOY', '루틴'),
('음악 크게 틀고 따라 부르기', 'JOY', '음악'),
('매번 하던 거 살짝 변주주기', 'JOY', '도전'),
('밝은 색 옷 입어보기', 'JOY', '루틴'),
('꽃이나 식물 바라보기', 'JOY', '휴식'),
('오늘 나를 칭찬하기', 'JOY', '루틴'),
('좋아하는 사람에게 안부 전하기', 'JOY', '사회'),
('짧은 댄스 해보기', 'JOY', '운동'),
('맛있는 음료 만들어 마시기', 'JOY', '루틴'),
('3년 전 추억 사진 꺼내보기', 'JOY', '휴식'),
('그네 타기', 'JOY', '루틴'),
('마음에 드는 글귀 필사하기', 'JOY', '루틴'),
('누군가에게 작은 선물하기', 'JOY', '사회'),
('내일 먹을 음식 정하기', 'JOY', '창작'),
('간단한 보드게임 하기', 'JOY', '놀이'),
('재밌는 썰 만들기', 'JOY', '창작'),
('내가 잘하는 것 3가지 적기', 'JOY', '루틴'),
('웃는 얼굴로 셀카 찍기', 'JOY', '루틴'),
('자잘한 쇼핑하기', 'JOY', '루틴'),
('평소에 안 입는 옷 입어보기', 'JOY', '도전'),
('평소 할까말까 했던 거 하기', 'JOY', '도전'),
('한 달 이상 연락 안 한 친구에게 연락하기', 'JOY', '도전'),
('방청소하기', 'JOY', '루틴'),
('옷정리하기', 'JOY', '루틴'),
('SNS 프로필 사진 바꾸기', 'JOY', '루틴');

