CREATE TABLE IF NOT EXISTS public.users (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email               VARCHAR(100) NOT NULL UNIQUE,
  password            VARCHAR(255) NOT NULL,
  nickname            VARCHAR(50)  NOT NULL,
  role                VARCHAR(20)  NOT NULL DEFAULT 'ROLE_USER',
  birth_date          DATE         NOT NULL,
  security_answer     VARCHAR(100) NOT NULL DEFAULT '',
  music_preferences   TEXT[]       NOT NULL,
  dark_mode           BOOLEAN      NOT NULL DEFAULT false,
  created_at          TIMESTAMP    NOT NULL DEFAULT now(),
  profile_image       bytea,
  profile_image_url   VARCHAR(255),
  character           VARCHAR(20)  NOT NULL DEFAULT 'piano'
);

CREATE TABLE IF NOT EXISTS public.genres (
  id   SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS public.user_genres (
  user_id  BIGINT NOT NULL,
  genre_id INTEGER NOT NULL,
  PRIMARY KEY (user_id, genre_id),
  FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
  FOREIGN KEY (genre_id) REFERENCES public.genres(id) ON DELETE CASCADE
);
