CREATE TABLE diaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    date DATE NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT uk_user_date UNIQUE (user_id, date),
    CONSTRAINT fk_user_diary FOREIGN KEY (user_id) REFERENCES users(id)
    CONSTRAINT fk_user_diary FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE

);
