CREATE TABLE diaries (
    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    content TEXT NOT NULL,
    date    DATE NOT NULL,
    user_id BIGINT NOT NULL,

    -- 유니크 제약
    CONSTRAINT uk_user_date UNIQUE (user_id, date),

    -- 외래키 제약 (ON DELETE CASCADE 포함, 쉼표 주의)
    CONSTRAINT fk_user_diary
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);
